# -*- coding: utf-8 -*-
"""лаб2_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10DzNnfiJlPBmz5l1jQYkiV41LXYtyFox
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# Открываем видеофайл
cap = cv2.VideoCapture('catball.mp4')

# Получаем параметры видео
fps = cap.get(cv2.CAP_PROP_FPS)
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

# Создаем VideoWriter для сохранения результата
out = cv2.VideoWriter('output_with_yellow_ball.mp4', cv2.VideoWriter_fourcc(*'mp4v'), fps, (width, height))

frame_count = 0  # Счетчик кадров

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    # Обрабатываем каждый пятый кадр
    if frame_count % 5 == 0:
        # Преобразуем кадр в цветовое пространство HSV
        hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)

        # Определяем диапазон желтого цвета в HSV
        lower_yellow = np.array([20, 100, 100])
        upper_yellow = np.array([30, 255, 255])

        # Создаем маску для желтого цвета
        mask = cv2.inRange(hsv, lower_yellow, upper_yellow)

        # Находим контуры на маске
        contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

        if contours:
            # Находим внешний контур
            largest_contour = max(contours, key=cv2.contourArea)

            # Рисуем контур на оригинальном кадре
            cv2.drawContours(frame, [largest_contour], -1, (0, 255, 0), 2)  # Рисуем контур зеленым цветом

            # Вычисляем моменты для нахождения центра масс
            M = cv2.moments(largest_contour)
            if M["m00"] != 0:
                cX = int(M["m10"] / M["m00"])
                cY = int(M["m01"] / M["m00"])
                # Рисуем центр масс
                cv2.circle(frame, (cX, cY), 5, (255, 0, 0), -1)  # Рисуем центр масс синим цветом

                # Отображаем координаты центра масс
                cv2.putText(frame, f'Center: ({cX}, {cY})', (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 255), 2)
            else:
                cv2.putText(frame, 'No ball detected', (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 255), 2)
        else:
            cv2.putText(frame, 'No ball detected', (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 255), 2)

        # Сохраняем кадр с контурами в новый видеофайл
        out.write(frame)

        # Отображаем кадр с контурами
        cv2_imshow(frame)

        # Пауза для отображения
        cv2.waitKey(1)

    frame_count += 1  # Увеличиваем счетчик кадров

# Освобождаем ресурсы
cap.release()
out.release()